#!/usr/bin/env bash
#
# ai-prohibited-tools-check.sh
#
# Purpose: Detect usage of prohibited AI code-generation tools in codebase
# Usage: ./ai-prohibited-tools-check.sh [--strict] [--repo-path <path>]
# Exit Codes: 0 = clean, 1 = violations found, 2 = error
#
# This script implements Section 14.6 (Prohibited External AI Tool Classes)
# from security-policy.md
#
# Integration Points:
# - Pre-commit hook: Scan staged files before commit
# - CI/CD pipeline: Scan full repository on PR
# - Security audit: Manual periodic scans
#
set -euo pipefail

# Configuration
STRICT_MODE=false
REPO_PATH="."
VIOLATIONS_FOUND=false

# Prohibited tool patterns (Section 14.6.1)
# These patterns indicate usage of unvetted AI tools
declare -a PROHIBITED_PATTERNS=(
    # Aggregator services
    "chawd\.ai"
    "chad\.ai"
    "chatgpt-unofficial"
    "free-gpt"
    "gpt-free"

    # Unvetted browser extensions
    "ai-enhancer-extension"
    "super-ai-assistant"
    "turbo-copilot"

    # Self-hosted without security
    "localhost:11434"  # Ollama default (allowed only if air-gapped)
    "127\.0\.0\.1:8080/ai"

    # Known risky endpoints
    "api\.unvetted-ai\.com"
    "free-ai-api\.xyz"

    # Code comments indicating prohibited tool usage
    "generated by chawd"
    "generated by chad"
    "from free ai tool"
    "from unvetted ai"
)

# Approved tool patterns (Section 14.6.3) - exclude from violations
declare -a APPROVED_PATTERNS=(
    "claude\.ai"
    "api\.anthropic\.com"
    "api\.openai\.com"
    "copilot\.github\.com"
    "github\.com/features/copilot"
    "codewhisperer\.aws"
    "gemini\.google\.com"
)

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Functions
usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Detect usage of prohibited AI code-generation tools in codebase.
Implements Section 14.6 (Prohibited External AI Tool Classes) from security-policy.md.

OPTIONS:
    --strict            Exit with error even for warnings
    --repo-path PATH    Scan repository at PATH (default: current directory)
    --help              Show this help message

EXAMPLES:
    # Pre-commit hook usage
    $(basename "$0") --strict

    # CI/CD pipeline usage
    $(basename "$0") --repo-path /workspace/repo

    # Manual audit
    $(basename "$0")

EXIT CODES:
    0    No violations found
    1    Violations found
    2    Error in execution

INTEGRATION:
    Pre-commit hook:    .git/hooks/pre-commit
    CI/CD pipeline:     .github/workflows/security-scan.yml
    Git hook:           .pre-commit-config.yaml
EOF
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*" >&2
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_violation() {
    local file="$1"
    local line="$2"
    local pattern="$3"
    local severity="${4:-HIGH}"

    VIOLATIONS_FOUND=true

    echo -e "${RED}[VIOLATION]${NC} $severity"
    echo "  File:    $file"
    echo "  Line:    $line"
    echo "  Pattern: $pattern"
    echo "  Context: $(sed -n "${line}p" "$file" 2>/dev/null | sed 's/^[ \t]*//')"
    echo ""
}

is_approved_pattern() {
    local text="$1"
    for approved in "${APPROVED_PATTERNS[@]}"; do
        if echo "$text" | grep -qE "$approved"; then
            return 0  # Is approved
        fi
    done
    return 1  # Not approved
}

scan_file() {
    local file="$1"
    local found_violations=false

    # Skip binary files, node_modules, .git, etc.
    if file "$file" | grep -qE "binary|executable"; then
        return 0
    fi

    if [[ "$file" == *"node_modules"* ]] || [[ "$file" == *".git"* ]] || [[ "$file" == *"__pycache__"* ]]; then
        return 0
    fi

    # Scan for prohibited patterns
    for pattern in "${PROHIBITED_PATTERNS[@]}"; do
        local matches
        matches=$(grep -nE "$pattern" "$file" 2>/dev/null || true)

        if [[ -n "$matches" ]]; then
            # Check if this is actually an approved usage
            while IFS=: read -r line_num matched_text; do
                if ! is_approved_pattern "$matched_text"; then
                    log_violation "$file" "$line_num" "$pattern" "HIGH"
                    found_violations=true
                fi
            done <<< "$matches"
        fi
    done

    return 0
}

scan_git_history() {
    log_info "Scanning Git history for prohibited tool indicators..."

    # Check commit messages
    local prohibited_commits
    prohibited_commits=$(git log --all --oneline --grep="chawd\|chad\|free.ai" -i 2>/dev/null || true)

    if [[ -n "$prohibited_commits" ]]; then
        log_warning "Found potentially problematic commit messages:"
        echo "$prohibited_commits"
        echo ""
        if [[ "$STRICT_MODE" == "true" ]]; then
            VIOLATIONS_FOUND=true
        fi
    fi

    # Check for suspicious URLs in commit diffs
    local suspicious_diffs
    suspicious_diffs=$(git log --all -p | grep -E "https?://(chawd|chad|free-ai)" || true)

    if [[ -n "$suspicious_diffs" ]]; then
        log_warning "Found prohibited tool URLs in commit history"
        if [[ "$STRICT_MODE" == "true" ]]; then
            VIOLATIONS_FOUND=true
        fi
    fi
}

scan_network_config() {
    log_info "Scanning network configurations for prohibited endpoints..."

    # Check for proxy configurations pointing to prohibited services
    local config_files=(
        ".npmrc"
        ".yarnrc"
        ".curlrc"
        ".wgetrc"
        "pip.conf"
        "poetry.toml"
    )

    for config in "${config_files[@]}"; do
        if [[ -f "$REPO_PATH/$config" ]]; then
            for pattern in "${PROHIBITED_PATTERNS[@]}"; do
                if grep -qE "$pattern" "$REPO_PATH/$config" 2>/dev/null; then
                    log_violation "$REPO_PATH/$config" "0" "$pattern" "CRITICAL"
                fi
            done
        fi
    done
}

check_environment_variables() {
    log_info "Checking environment variables for prohibited tool references..."

    # Common environment variable patterns
    local env_patterns=(
        "CHAWD_API_KEY"
        "CHAD_TOKEN"
        "FREE_AI_KEY"
        "UNVETTED_AI_ENDPOINT"
    )

    for var in "${env_patterns[@]}"; do
        if env | grep -qE "^$var="; then
            log_violation "environment" "0" "$var" "CRITICAL"
        fi
    done
}

generate_report() {
    echo ""
    echo "========================================"
    echo "Prohibited AI Tool Detection Report"
    echo "========================================"
    echo "Repository: $REPO_PATH"
    echo "Scan Date:  $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
    echo "Policy Ref: security-policy.md Section 14.6"
    echo "Script:    ai-prohibited-tools-check.sh"
    echo ""

    if [[ "$VIOLATIONS_FOUND" == "true" ]]; then
        echo -e "${RED}Result: VIOLATIONS FOUND${NC}"
        echo ""
        echo "ACTION REQUIRED:"
        echo "1. Review violations listed above"
        echo "2. Remove prohibited tool references from code and configs"
        echo "3. If tool usage was legitimate, request exception via security team"
        echo "4. Update approved-ai-tools.md if new tool should be allowed"
        echo ""
        echo "For approved alternatives, see:"
        echo "  - security-policy.md Section 14.6.6 (Developer Resources)"
        echo "  - approved-ai-tools.md (Approved Tool Registry)"
        echo "  - ai-tool-policy-quick-reference.md (Quick Reference Guide)"
        echo ""
        echo "Support:"
        echo "  - Email: security@organization.com"
        echo "  - Slack: #security-policy"
        echo ""
        return 1
    else
        echo -e "${GREEN}Result: CLEAN${NC}"
        echo "No prohibited AI tool references detected."
        echo ""
        echo "This repository complies with Section 14.6 policy requirements."
        echo ""
        return 0
    fi
}

scan_staged_files() {
    log_info "Scanning staged files (pre-commit mode)..."

    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        log_warning "Not a Git repository, skipping staged file scan"
        return 0
    fi

    local staged_files
    staged_files=$(git diff --cached --name-only --diff-filter=ACM 2>/dev/null || true)

    if [[ -z "$staged_files" ]]; then
        log_info "No staged files to scan"
        return 0
    fi

    while IFS= read -r file; do
        if [[ -f "$file" ]]; then
            scan_file "$file"
        fi
    done <<< "$staged_files"
}

validate_file_extensions() {
    log_info "Validating file extensions and types..."

    # Check for suspicious file types that might contain prohibited tool configs
    local suspicious_files
    suspicious_files=$(find "$REPO_PATH" -type f \
        \( -name "*.env*" -o -name "*.config" -o -name "*.conf" -o -name "*.ini" \) \
        ! -path "*/node_modules/*" \
        ! -path "*/.git/*" \
        ! -path "*/venv/*" \
        2>/dev/null || true)

    if [[ -n "$suspicious_files" ]]; then
        while IFS= read -r file; do
            for pattern in "${PROHIBITED_PATTERNS[@]}"; do
                if grep -qE "$pattern" "$file" 2>/dev/null; then
                    log_violation "$file" "0" "$pattern" "HIGH"
                fi
            done
        done <<< "$suspicious_files"
    fi
}

check_package_manifests() {
    log_info "Scanning package manifests for prohibited tool dependencies..."

    local manifest_files=(
        "package.json"
        "requirements.txt"
        "Pipfile"
        "pyproject.toml"
        "Cargo.toml"
        "go.mod"
        "pom.xml"
        "build.gradle"
    )

    for manifest in "${manifest_files[@]}"; do
        if [[ -f "$REPO_PATH/$manifest" ]]; then
            for pattern in "${PROHIBITED_PATTERNS[@]}"; do
                if grep -qE "$pattern" "$REPO_PATH/$manifest" 2>/dev/null; then
                    log_violation "$REPO_PATH/$manifest" "0" "$pattern" "CRITICAL"
                fi
            done
        fi
    done
}

# Main execution
main() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --strict)
                STRICT_MODE=true
                shift
                ;;
            --repo-path)
                REPO_PATH="$2"
                shift 2
                ;;
            --help)
                usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 2
                ;;
        esac
    done

    # Validate repository path
    if [[ ! -d "$REPO_PATH" ]]; then
        log_error "Repository path does not exist: $REPO_PATH"
        exit 2
    fi

    cd "$REPO_PATH" || exit 2

    log_info "Starting prohibited AI tool detection scan..."
    log_info "Repository: $REPO_PATH"
    log_info "Strict mode: $STRICT_MODE"
    echo ""

    # Run scans
    log_info "Scanning source files..."
    while IFS= read -r -d '' file; do
        scan_file "$file"
    done < <(find "$REPO_PATH" -type f \
        ! -path "*/node_modules/*" \
        ! -path "*/.git/*" \
        ! -path "*/__pycache__/*" \
        ! -path "*/venv/*" \
        ! -path "*/.venv/*" \
        ! -path "*/dist/*" \
        ! -path "*/build/*" \
        ! -path "*/target/*" \
        ! -path "*/.idea/*" \
        ! -path "*/.vscode/*" \
        ! -path "*/rules/security-policy.md" \
        ! -path "*/rules/approved-ai-tools.md" \
        ! -path "*/rules/ai-tool-policy-quick-reference.md" \
        ! -path "*/rules/ai-workflow-policy.md" \
        ! -path "*/rules/references/*" \
        ! -path "*/rules/templates/*" \
        -print0)

    # Scan Git history (if repo is a Git repository)
    if [[ -d "$REPO_PATH/.git" ]]; then
        scan_git_history
    fi

    # Scan network configurations
    scan_network_config

    # Check environment variables
    check_environment_variables

    # Validate file extensions
    validate_file_extensions

    # Check package manifests
    check_package_manifests

    # Generate final report
    generate_report
}

# Run main function
main "$@"
